theme: jekyll-theme-cayman
title: Multi-Modal Multi-Channel Corpus 
description: Solving Cocktail Party Problem -- using multi-channel audio and visual data with transcriptions, speaker labels and location information 
