theme: jekyll-theme-cayman
title: Multi-Modal Multi-Channel Corpus for Cocktail Party Problem
description: multi-channel audio and visual data with transcriptions, speaker's label and directional information 
