theme: jekyll-theme-cayman
title: Multi-Modal Multi-Channel Corpus for Cocktail Party Problem
description: multi-channel audio and visual data with transcriptions, speakers\' label and directional information 
